### ISSUE TITLE
undefined: sync.Map

### ISSUE THREAD

**Issue by kishorevaishnav** [Equanox/gotron#17]
```
# github.com/Equanox/gotron
../../../../go/src/github.com/Equanox/gotron/gotron.go:47: undefined: sync.Map
```

above is the error I get when I execute the normal code copied from README.MD.  BTW, my `go version` is `go version go1.8.3 darwin/amd64`

**Comment by puengel** [comment]
Hi,
Thanks for your interest in gotron. 
Sync.map comes with go version 1.9 or higher.
I suggest using go version 1.11 to also benefit from go modules.
Cheers,
Puengel

**Comment by kishorevaishnav** [comment]
Hi @puengel , 

Thanks. It did **WORKED** after upgrading go to 1.11 and with small tweak. I was getting this error.
```sh
# github.com/Equanox/gotron
../../../../go/src/github.com/Equanox/gotron/gotron.go:121:12: assignment mismatch: 2 variables but 1 values
```

and hence I updated the code like the below.

![image](https://user-images.githubusercontent.com/136354/50453853-68857880-08f8-11e9-8c20-74ff8fb9c424.png)

```golang
	u := uuid.NewV4()
	// errz.Fatal(err)
```

**Comment by puengel** [comment]
Seems like you are using an older version of github.com/satori/go.uuid than gotron is referencing. See correct versions in go.mod file. Please try `go get ./...` in gotron home directory to update to the correct versions of modules.

**Comment by kishorevaishnav** [comment]
👍 Thanks it worked as you suggested. Hence I am closing this issue. Sorry for the noise.
